### ISSUE TITLE
:bug: 호스트의 /v1/* 경로에만 접근 가능한 문제

### ISSUE THREAD

**Issue by joohongpark** [42Sunny/checkin_v3_back#18]
## Symptom
- dev 실 서버에서 운용중인 HTTP 서버에 외부에서 접근할 때 /v1/ 외에 다른 경로엔 접근이 차단되는 문제

## Environment (OS / Browser)
-  AWS EC2

**Comment by 6mn12j** [comment]
### 해결법
로드밸런스 리스너 규칙 수정 
- EC2 로드밸런스 리스너 규칙으로 `/v1/*또는/v1*` 만 들어올 수 있게 설정 되어 있었다.
 - 443포트의 규칙에 v3 를 추가함
 - 리전을 버지니아 북부가 아닌 서울로 변경해야 해당 로드밸런스들이 보임.
 - 규칙을 수정/추가 하기 위해서는 권한이 필요함.
